#!/bin/sh

exec 2>&1

if [ -s /run/paray/tunnel-token ]; then
    exec s6-setuidgid paray \
        env -i \
        PATH=/usr/local/bin:/usr/bin:/bin \
        HOME=/run/paray/home \
        /usr/local/bin/cloudflared \
        --no-autoupdate \
        tunnel \
        --edge-ip-version auto \
        --protocol http2 \
        --metrics 127.0.0.1:20000 \
        run \
        --token-file /run/paray/tunnel-token
fi

exec s6-pause