#!/bin/sh

exec 2>&1

exec s6-setuidgid paray \
    env -i \
    PATH=/usr/local/bin:/usr/bin:/bin \
    HOME=/run/paray/home \
    XRAY_LOCATION_ASSET=/usr/local/share/xray \
    /usr/local/bin/xray run \
    -config /run/paray/config.json